name:                seventh-guest
version:             0.1.0.0
github:              "ublubu/seventh-guest"
license:             BSD3
author:              "Kynan Rilee"
maintainer:          "kynan.rilee@gmail.com"
copyright:           "2018 Kynan Rilee"

extra-source-files:
- README.md

synopsis:            Microscope Puzzle from 7th Guest
category:            Game

description:         Please see the README on Github at <https://github.com/githubuser/seventh-guest#readme>

dependencies:
- base >= 4.7 && < 5
- classy-prelude
- containers
- lens
- vector
- text

executables:
  microscope-puzzle:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
